server:
  port: 5999
  appRoot: "/bucky"

statsd:
  host: 'localhost'
  port: 8125

modules:
  app:
    - ./modules/trustProxy
    - ./modules/auth
    - ./modules/collectors

  collectors:
    - ./modules/collectionLogger
    - ./modules/statsd
